CREATE TYPE "degree_level" AS ENUM (
  'BACHELOR',
  'MASTER',
  'PHD'
);

CREATE TYPE "gender" AS ENUM (
  'M',
  'F',
  'O'
);

CREATE TYPE "payment_method" AS ENUM (
  'CASH',
  'CARD'
);

CREATE TYPE "released_to" AS ENUM (
  'SUPERVISOR',
  'POLICE',
  'COURT'
);

CREATE TABLE "specialization" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) UNIQUE NOT NULL
);

CREATE TABLE "field" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) UNIQUE NOT NULL
);

CREATE TABLE "specialization_field" (
  "specialization_id" int,
  "field_id" int,
  PRIMARY KEY ("specialization_id", "field_id")
);

CREATE TABLE "university" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) UNIQUE NOT NULL,
  "specialization_id" int
);

CREATE TABLE "faculty" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "university_id" int
);

CREATE TABLE "faculty_field" (
  "faculty_id" int,
  "field_id" int,
  PRIMARY KEY ("faculty_id", "field_id")
);

CREATE TABLE "training_center" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) UNIQUE NOT NULL,
  "email" varchar(120),
  "phone" varchar(32),
  "street" varchar(120),
  "number" varchar(16),
  "city" varchar(120)
);

CREATE TABLE "candidate" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(80),
  "last_name" varchar(80),
  "jmbg" char(13) UNIQUE NOT NULL,
  "birth_date" date,
  "residence" varchar(120),
  "phone" varchar(32),
  "email" varchar(120),
  "faculty_id" int,
  "degree_level" degree_level,
  "training_center_id" int
);

CREATE TABLE "therapy_area" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) UNIQUE NOT NULL
);

CREATE TABLE "therapist" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "candidate_id" int,
  "first_name" varchar(80),
  "last_name" varchar(80),
  "jmbg" char(13) UNIQUE NOT NULL,
  "birth_date" date,
  "residence" varchar(120),
  "phone" varchar(32),
  "email" varchar(120),
  "certification_date" date,
  "therapy_area_id" int,
  "training_center_id" int
);

CREATE TABLE "supervision" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supervisor_id" int,
  "candidate_id" int,
  "start_date" date,
  "end_date" date
);

CREATE TABLE "client" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(80),
  "last_name" varchar(80),
  "birth_date" date,
  "gender" gender,
  "email" varchar(120),
  "phone" varchar(32),
  "prev_therapy" boolean,
  "problem_desc" text
);

CREATE TABLE "currency" (
  "code" char(3) PRIMARY KEY,
  "name" varchar(64)
);

CREATE TABLE "currency_rate" (
  "currency_code" char(3),
  "rate_date" date,
  "rsd_rate" decimal(12,4),
  PRIMARY KEY ("currency_code", "rate_date")
);

CREATE TABLE "hourly_rate_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "therapist_id" int,
  "valid_from" date,
  "price_per_hour" decimal(10,2),
  "currency_code" char(3)
);

CREATE TABLE "session" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int,
  "therapist_id" int,
  "candidate_id" int,
  "session_datetime" datetime,
  "duration_min" int,
  "notes" text,
  "hourly_rate_id" int
);

CREATE TABLE "psychological_test" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "area" varchar(120),
  "name" varchar(120) UNIQUE,
  "price" decimal(10,2)
);

CREATE TABLE "session_test" (
  "session_id" int,
  "test_id" int,
  "result" varchar(120),
  PRIMARY KEY ("session_id", "test_id")
);

CREATE TABLE "payment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int,
  "session_id" int,
  "installment_no" int,
  "purpose" varchar(120),
  "currency_code" char(3),
  "payment_method" payment_method,
  "amount" decimal(12,2),
  "payment_timestamp" datetime
);

CREATE TABLE "session_data_release" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" int,
  "released_to" released_to,
  "release_date" date,
  "reason" text
);

CREATE INDEX ON "university" ("specialization_id");

CREATE UNIQUE INDEX ON "faculty" ("name", "university_id");

CREATE INDEX ON "supervision" ("candidate_id", "start_date");

CREATE UNIQUE INDEX ON "hourly_rate_history" ("therapist_id", "valid_from");

CREATE INDEX ON "session" ("client_id", "session_datetime");

CREATE UNIQUE INDEX ON "payment" ("session_id", "installment_no");

COMMENT ON TABLE "specialization_field" IS 'PK = specialization_id + field_id';

ALTER TABLE "specialization_field" ADD FOREIGN KEY ("specialization_id") REFERENCES "specialization" ("id");

ALTER TABLE "specialization_field" ADD FOREIGN KEY ("field_id") REFERENCES "field" ("id");

ALTER TABLE "university" ADD FOREIGN KEY ("specialization_id") REFERENCES "specialization" ("id");

ALTER TABLE "faculty" ADD FOREIGN KEY ("university_id") REFERENCES "university" ("id");

ALTER TABLE "faculty_field" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculty" ("id");

ALTER TABLE "faculty_field" ADD FOREIGN KEY ("field_id") REFERENCES "field" ("id");

ALTER TABLE "candidate" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculty" ("id");

ALTER TABLE "candidate" ADD FOREIGN KEY ("training_center_id") REFERENCES "training_center" ("id");

ALTER TABLE "therapist" ADD FOREIGN KEY ("candidate_id") REFERENCES "candidate" ("id");

ALTER TABLE "therapist" ADD FOREIGN KEY ("therapy_area_id") REFERENCES "therapy_area" ("id");

ALTER TABLE "therapist" ADD FOREIGN KEY ("training_center_id") REFERENCES "training_center" ("id");

ALTER TABLE "supervision" ADD FOREIGN KEY ("supervisor_id") REFERENCES "therapist" ("id");

ALTER TABLE "supervision" ADD FOREIGN KEY ("candidate_id") REFERENCES "candidate" ("id");

ALTER TABLE "currency_rate" ADD FOREIGN KEY ("currency_code") REFERENCES "currency" ("code");

ALTER TABLE "hourly_rate_history" ADD FOREIGN KEY ("therapist_id") REFERENCES "therapist" ("id");

ALTER TABLE "hourly_rate_history" ADD FOREIGN KEY ("currency_code") REFERENCES "currency" ("code");

ALTER TABLE "session" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id");

ALTER TABLE "session" ADD FOREIGN KEY ("therapist_id") REFERENCES "therapist" ("id");

ALTER TABLE "session" ADD FOREIGN KEY ("candidate_id") REFERENCES "candidate" ("id");

ALTER TABLE "session" ADD FOREIGN KEY ("hourly_rate_id") REFERENCES "hourly_rate_history" ("id");

ALTER TABLE "session_test" ADD FOREIGN KEY ("session_id") REFERENCES "session" ("id");

ALTER TABLE "session_test" ADD FOREIGN KEY ("test_id") REFERENCES "psychological_test" ("id");

ALTER TABLE "payment" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id");

ALTER TABLE "payment" ADD FOREIGN KEY ("session_id") REFERENCES "session" ("id");

ALTER TABLE "payment" ADD FOREIGN KEY ("currency_code") REFERENCES "currency" ("code");

ALTER TABLE "session_data_release" ADD FOREIGN KEY ("session_id") REFERENCES "session" ("id");
